[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxagaudiotool={path="../"}
robotics_lib = { path = "../../../Advanced-Programming-2023/Robotic-Lib" }